name: Django CI

version: 2
jobs:
 build:
  working_directory: ~/tt-server
docker:
  - image: circleci/python3.6
    environment:
        # Enviroment Variables
steps:
  - checkout
  - run:
      command: pipenv install
  - run:
      command: "echo mkdir /tmp/artifacts"
  - run:
      command: |
        pipenv run "coverage run manage.py test --parallel=4"
        pipenv run "coverage combine"
        pipenv run "coverage report -m"
        pipenv run "coverage html -d /tmp/artifacts"
        pipenv run "coveralls"
  - store_artifacts:
      path: /tmp/artifactsments.txt
    - name: Run Tests
      run: |
        python3 manage.py test
